# Generated by Django 6.0.1 on 2026-02-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_students_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
